# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.TextField()),
                ('App_Version', models.TextField()),
                ('Platform', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.TextField()),
                ('Model_OS', models.TextField()),
                ('Error_Type', models.TextField()),
                ('Error_Message', models.TextField()),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Status', models.TextField()),
                ('Device_Model', models.TextField()),
                ('App_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='StationerryBackend.App')),
            ],
        ),
    ]
