# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationerryBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='App_Version',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='Date',
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
