# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StationerryBackend', '0002_auto_20160519_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_Name', models.TextField(primary_key=True, serialize=False)),
                ('Password', models.TextField()),
                ('Email', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='Platform',
        ),
        migrations.AddField(
            model_name='app',
            name='Platform',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='App_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='StationerryBackend.Users'),
        ),
    ]
