# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationerryBackend', '0003_auto_20160527_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='Model_Name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugreport',
            name='Model_OS',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
