# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-27 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationerryBackend', '0004_auto_20160527_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Real_Name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
