# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StationerryBackend', '0006_auto_20160602_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
