# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StationerryBackend', '0008_auto_20160602_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to=settings.AUTH_USER_MODEL),
        ),
    ]
