# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StationerryBackend', '0009_auto_20160602_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='User_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unused_owns', to='StationerryBackend.Users'),
        ),
    ]
